### ISSUE TITLE
The status always shows 'Retrieving donation data'

### ISSUE THREAD

**Issue by sagarjauhari** [ComputeForHumanity/compute-for-humanity-app#21] opened 2015-10-15 15:51 UTC
![image](https://cloud.githubusercontent.com/assets/1958807/10519258/0a6b5408-7333-11e5-8e61-dea974f5b005.png)

Since the time I have installed the app, it has only showed me this status.

**Comment by JacobEvelyn** [comment] 2015-10-20 22:56
Interesting; I haven't heard of anyone else experiencing this. What do your firewall settings look like?

**Comment by sagarjauhari** [comment] 2015-10-21 02:39
I have firewall turned on but I have enabled connections for this
application.

On Tue, Oct 20, 2015 at 6:56 PM, Jacob Evelyn notifications@github.com
wrote:

> Interesting; I haven't heard of anyone else experiencing this. What do
> your firewall settings look like?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ComputeForHumanity/compute-for-humanity-app/issues/21#issuecomment-149725552
> .

## 

_Sagar Jauhari_
https://www.linkedin.com/in/sagarjauhari

**Comment by JacobEvelyn** [comment] 2015-10-22 00:00
Ah, it looks like this is being caused by new OS X behavior that makes requests fail when they aren't HTTPS or listed as a special exception. (This behavior is new in El Capitan.) I'll get a fix out shortly.

Thanks for the bug report!

**Comment by JacobEvelyn** [comment] 2015-10-22 00:36
This issue has been fixed in Compute for Humanity version 1.12. Unfortunately you'll have to install this version manually if you're on El Capitan, as described in #20 (since the underlying cause of both issues is the same).

**Closed as completed by JacobEvelyn** 2015-10-22 00:36 UTC
