### ISSUE TITLE
'Check for update' show error

### ISSUE THREAD

**Issue by sagarjauhari** [ComputeForHumanity/compute-for-humanity-app#22] opened 2015-10-15 15:52 UTC
![image](https://cloud.githubusercontent.com/assets/1958807/10519330/2c2563b8-7333-11e5-826a-e623a51f0cf7.png)

whenever I check for updates

**Comment by JacobEvelyn** [comment] 2015-10-15 18:24
Thanks for the bug report! Are you on El Capitan?

**Comment by sagarjauhari** [comment] 2015-10-16 00:12
Yes

**Comment by JacobEvelyn** [comment] 2015-10-20 22:54
Great, thanks for the info. This appears to be a duplicate of #20. I'll post progress on that thread.

**Closed as completed by JacobEvelyn** 2015-10-20 22:54 UTC
